# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_segment <- function(name) {
    .Call(`_interprocess_create_segment`, name)
}

write_array <- function(name, object_name, values) {
    invisible(.Call(`_interprocess_write_array`, name, object_name, values))
}

read_array <- function(name, object_name) {
    .Call(`_interprocess_read_array`, name, object_name)
}

